### ISSUE TITLE
Totem Pop Counter

### ISSUE THREAD

**Issue by slipll** [UneasyVanilla/UneasyNetwork#3]
### What server does this feature request will applied to?

Vanilla Server

### Is your feature request related to a problem?

I would like this to be added as it a mainly accepted mod in pvp use and only keeps a totem pop counter

### Describe the solution you'd like.

The Totem Pop Counter Mod to be put on the allowed mods list
https://modrinth.com/mod/totemcounter

### Describe alternatives you've considered.

None

**Comment by MsEDok** [comment]
This mod include an "item counter" which imo is giving the user too much info on how many totem they have left.
