### ISSUE TITLE
Allow Xaero's world map

### ISSUE THREAD

**Issue by Miljandro** [UneasyVanilla/UneasyNetwork#4]
### What server does this feature request will applied to?

Vanilla Server

### Is your feature request related to a problem?

It normally isn't allowed due to being able to xray in the nether (as it shows a top down map from the nether roof)

### Describe the solution you'd like.

Allowing xaero's since I found out that you can disable nether cave maps in settings, if the player does xray with it they get the banhammer

### Describe alternatives you've considered.

None

**Comment by MsEDok** [comment]
This will mostlikely not getting added untill the dev of Xaero's world map "force" use fairplay feature on the worldmap instead of a config, ingame toggle.

**Comment by MsEDok** [comment]
This will mostlikely not getting added untill the dev of Xaero's world map "force" use fairplay feature on the worldmap instead of a config, ingame toggle.
