### ISSUE TITLE
Allow itemscroller

### ISSUE THREAD

**Issue by Miljandro** [UneasyVanilla/UneasyNetwork#5]
### What server does this feature request will applied to?

Vanilla Server

### Is your feature request related to a problem?

It got banned recently due to the masscrafting potential, although it is still mostly a qol mod that isn't very cheaty

### Describe the solution you'd like.

Allowing it but making it the player's responsibility to not use masscrafting (similar to not using litematica easy place)

### Describe alternatives you've considered.

None

**Comment by MsEDok** [comment]
It currently being worked on for itemscroller to remove some of the feature that we consider giving too much advantage (autocrafting etc)
Will most likely be a repo on here soon

**Comment by MsEDok** [comment]
It currently being worked on for itemscroller to remove some of the feature that we consider giving too much advantage (autocrafting etc)
Will most likely be a repo on here soon

**Comment by MsEDok** [comment]
Added bf9c1ac07b7ead334e26d91185f924ce4244b2fb
