### ISSUE TITLE
Add "Enhanced Block Entities" to the allowed mod list.

### ISSUE THREAD

**Issue by Trigithy** [UneasyVanilla/UneasyNetwork#9]
### What server does this feature request will applied to?

Vanilla Server

### Is your feature request related to a problem?

No. (although my FPS drops by 10 when I enter my storage room)

### Describe the solution you'd like.

Add 'Enhanced Block Entities' to the allowed mod list.
Curseforge link: https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities

This mod allows you to replace some block entities with baked block models which improves rendering drastically.

### Describe alternatives you've considered.

Destroying every chest in my storage room for the sake of higher FPS.

**Comment by MsEDok** [comment]
added 210008c17908a831f85714e51a212b2e2bb3f420
